### ISSUE TITLE
do we need pString / PString?

### ISSUE THREAD

**Issue by DougBurke** [gicentre/elm-vegalite#13]
My slow march through the Vega-Lite gallery continues. Today's adventure is https://vega.github.io/vega-lite/examples/layer_bar_annotations.html which includes

```
        "encoding": {
          "x": {
            "value": "width"
          },
```

I think this means there should be a `pStr : String -> PositionChannel` to match `pNum` (or some similar name), but maybe I'm missing something **really** obvious.

**Comment by jwoLondon** [comment]
Elm-vegalite has functions [pWidth](https://package.elm-lang.org/packages/gicentre/elm-vegalite/latest/VegaLite#pWidth) and [pHeight](https://package.elm-lang.org/packages/gicentre/elm-vegalite/latest/VegaLite#pHeight) that are used to reference a plot's width and height positions. This seemed safer than a general `pStr` option, but if you spot a case where arbitrary strings are required, feel free to reopen.
