### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by DougBurke** [gicentre/elm-vegalite#19]
From looking through the vega-lite 3.4.0 and 4.0.0 beta 0 schema, it looks like you are missing several symbol types. From the schema:

```
        "shape": {
          "description": "Shape of the point marks. Supported values include:\n- plotting shapes: `\"circle\"`, `\"square\"`, `\"cross\"`, `\"diamond\"`, `\"triangle-up\"`, `\"triangle-down\"`, `\"triangle-right\"`, or `\"triangle-left\"`.\n- the line symbol `\"stroke\"`\n- centered directional shapes `\"arrow\"`, `\"wedge\"`, or `\"triangle\"`\n- a custom [SVG path string](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths) (For correct sizing, custom shape paths should be defined within a square bounding box with coordinates ranging from -1 to 1 along both the x and y dimensions.)\n\n__Default value:__ `\"circle\"`",
          "type": "string"
        },
```

So missing - unless you've added them recently ;-) - are `arrow`, `stroke`, `triangle`, `triangle-left`, `triangle-right`, and `wedge` (although it's not clear how different triangle and triangle-up are to me).

**Comment by jwoLondon** [comment]
Thanks for spotting these (I must diff the various schema docs more regularly in the future).

I've now added them, with hopefully the expected names.

BTW: The difference between `triangle` and `triangle-up` is that only the former is centred on its centroid so it can be used for vector diagrams, once [VL includes an 'angle' channel](https://github.com/vega/vega-lite/issues/4548).
