### ISSUE TITLE
should columns just take an Int rather than Maybe Int as Null is not valid in the 3.3.0 schema

### ISSUE THREAD

**Issue by DougBurke** [gicentre/elm-vegalite#2]
At the moment you have `columns : Maybe Int -> ( VLProperty, Spec )` where a `Nothing` maps to a JSON Null value:

https://github.com/gicentre/elm-vegalite/blob/master/src/VegaLite.elm#L5964

The 3.3.0 schema doesn't allow Null here - there are multiple "columns" entries, all accepting a number only, e.g.

https://github.com/vega/schema/blob/master/vega-lite/v3.3.0.json#L6483
https://github.com/vega/schema/blob/master/vega-lite/v3.3.0.json#L11105

Should Nothing map to 0 (e.g. the description of the first case suggests 0 is a sensible value in that case, whether it is true for all uses of columns is a different question)? If so, then is the Maybe type still needed?

Or maybe we could ask the VegaLite folks to update the spec to allow a null here?

**Comment by jwoLondon** [comment]
Given there appears to be no move in VL4 to allow nulls, I've made a breaking change to `columns` to take a simple `int` rather than `Maybe int`. Documentation and examples updated accordingly.
