### ISSUE TITLE
add support for naturalEarth1 projection?

### ISSUE THREAD

**Issue by DougBurke** [gicentre/elm-vegalite#21]
In updating hvega to add "equalEarth" based on your change notes, I noticed that the [Vega-Lite 4.0.2 schema](https://github.com/vega/schema/blob/master/vega-lite/v4.0.2.json#L11944) includes support for the "naturalEarth1" projection type - that is https://github.com/d3/d3-geo#geoNaturalEarth1

The Vega-Lite documentation doesn't (currently) mention it at https://vega.github.io/vega-lite/docs/projection.html#projection-types

**Comment by jwoLondon** [comment]
Thanks Doug. Now added.
