### ISSUE TITLE
I think key needs more structure than just the field name

### ISSUE THREAD

**Issue by DougBurke** [gicentre/elm-vegalite#22]
This is from me just looking at `VegaLite.elm` rather than actually running it, so I may be missing something, but when adding `key` to hvega I found that the output was not valid according to the 4.0.2 schema. It looks like the `"key"` field takes an object and not a string name - e.g. 

https://github.com/vega/schema/blob/master/vega-lite/v4.0.2.json#L2612

and

https://vega.github.io/vega-lite/docs/encoding.html#key

I also haven't ever used the update functionality with Vega-Lite, to change an existing visualization (and am unlikely to do so in the near future), so I really don't know what I'm doing here ;-)

**Comment by jwoLondon** [comment]
Thanks. Finally got round to correcting this. Will be available in next major release (as this is technically a breaking change)
