### ISSUE TITLE
missing miLinearClosed?

### ISSUE THREAD

**Issue by DougBurke** [gicentre/elm-vegalite#24]
Continuing my trawl through your code to see what I've missed, I noted that it looks like the `LinearClosed` constructor is missing the "wrapper" function `miLinearClosed`

https://github.com/gicentre/elm-vegalite/blob/master/src/VegaLite.elm#L4529

ie I couldn't find something like

```
{-| Linear (straight) interpolation between points forming a polygon
-}
miLinearClosed : MarkInterpolation
miLinearClosed =
    LinearClosed
```

**Comment by jwoLondon** [comment]
Thanks very much for spotting this. Added to the next release.
