### ISSUE TITLE
labelAlign changes (hopefully informational only)

### ISSUE THREAD

**Issue by DougBurke** [gicentre/elm-vegalite#26]
Thought you might be interested in https://github.com/vega/vega-lite/issues/5717 / https://github.com/vega/vega-lite/pull/5798 - I don't think you need to do anything for `CAxLabelAlign` as Vega-Lite should now support what you create.

**Comment by jwoLondon** [comment]
Thanks for pointing this out and raising it with the Vega-Lite team. Yes, it looks like we have this covered with the existing API.
