### ISSUE TITLE
Does FacetChannel need more options (e.g. for spacing)?

### ISSUE THREAD

**Issue by DougBurke** [gicentre/elm-vegalite#29]
I was looking at updating my version of https://vega.github.io/vega-lite/examples/bar_grouped.html and found I couldn't handle (in @hvega@)

```
"encoding": {
    "column": {
      "field": "age", "type": "ordinal", "spacing": 10
    },
```

because of the `spacing` field. It looks like the facet types have been changed from 3.4.x

```
        "column": {
          "$ref": "#/definitions/FacetFieldDef",
          "description": "A field definition for the horizontal facet of trellis plots."
        },
```

to 4.x (here from 4.2)

```
        "column": {
          "$ref": "#/definitions/RowColumnEncodingFieldDef",
          "description": "A field definition for the horizontal facet of trellis plots."
        },
```

where things like \"column\" are described. So it looks like `FacetChannel` needs some additions (or I'm mis-reading things again).

**Comment by DougBurke** [comment]
This may be related to how you've decided to handle facet/flow in vega-lite - you have discussed this with me before.

**Comment by jwoLondon** [comment]
Thanks again for spotting this. While the spacing can be set as a configuration (`facoSpacing`), I hadn't spotted that VL4 had added direct property setting for faceted sub-plots. I've added `fSpacing`, `fAlign` and `fCenter` functions and equivalent type variants in the latest commit. 

Note also I have internally renamed the configuration type from `FSpacing` to `FCSpacing` to avoid a naming conflict with the non-config `FSpacing` type, but given type variants are exposed in hvega, I hope this doesn't cause you problems.
