### ISSUE TITLE
PPrecision should create a string, not a float, in the JSON output

### ISSUE THREAD

**Issue by DougBurke** [gicentre/elm-vegalite#3]
I am hoping this is an error in the Vega-Lite 3.3.0 specification - see https://github.com/vega/vega-lite/issues/5190 for a discussion - but PPrecision should be generating a string rather than a float.

(I've finally integrated your test suite into hvega, where I generate the JSON for each test and then compare it against the checked-in version to ensure the output hasn't changed; it means I have a bunch of JSON files I can easily validate against the Vega Lite schema, which finds the odd strange case like this)

**Comment by jwoLondon** [comment]
Thanks for raising this over on Vega-Lite. Looks like it will be solved in the next VL release https://github.com/vega/vega-lite/pull/5191 and the elm-vegalite and hvega specs can remain as is.
