### ISSUE TITLE
Do you need 'doSelectionField'/'doSelectionChannel' to go with 'doSelection'?

### ISSUE THREAD

**Issue by DougBurke** [gicentre/elm-vegalite#32]
In hvega I wanted to make a "context and detail" style plot where you could zoom in both the X and Y directions. Since the selection is projected across both channels, I couldn't just use `doSelection` on both axes (of the detail plot) as this just used the same range from the context plot for both axes. I ended up adding versions of `doSelection` which took either a field name or an encoding channel - e.g. something like `doSelectionField : String -> String -> ScaleDomain` and `doSelectionChannel : String -> Channel -> ScaleDomain` which create JSON objects `{"selection": selName, "field": fieldName}` or `{"selection": selName, "encoding": channel}`

Here is a not-very-informative example I used to check it worked (in this case I used my equivalents of both `doSelectionField` and `doSelectionChannel` just to check they worked; the VL documentation suggests only one is needed and the other could remain `doSelection`):

https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAuBOCGA7AzgMwPawLaQFxgG1hJ5k8oBPSAGigGN4AbOgV0fmgFNzI71kAFABMOLLADpoAC07R4ASkgBfALrVwUEXPLFknAI4tOiOt3zFSPabPg0oyObGjkADLUgPOAB1fiAjO4O6D74AGziAEwAHEpK6hCQAG58JhzkBBoQoBA5UFjwsADWPIwAlojc8bn2nIycdNCl6Ig6mdWQAEawLMhSrdXt5aXO5pAAHukukbShapTpALRTUbTLKnFtA5DGfELlAOZk+ATjdpBUapvt0BReZlDlXLCJTJBXEEpXG1s76HuI+36AygE1GqFKtSEVhk2ncNzuPEMSEackaiUqUHgY1KRzAiDYjG+wPOOkg4MhPCocNu90gSMQKI4pXRZyxOPI+MYhK+bSJWSukHyRR4dFKsDodRoAt+-0B5neIKBwKg5MYUPwMBhtiqyo8DEloyE6Hy5VJqvVUGssJqdQaTRaGq6PT6sR1xPhtPpjLR3AVfPaVHlyoS5spUuD9n192IRpNDrAulq9UazR4Tt6ZxlBzDroVCQ9iJYyOGTJZfp5uU+EEuCQAJMg6DJ8jwpNBoF5kLgAPRd9H7eDifbDKQsDriJpdhtN+C9zj9hZlLi9gAs4gAVshUyAlEA

**Comment by jwoLondon** [comment]
Thanks very much for this. I've added two functions `doSelectionChannel` and `doSelectionField` as you suggest.
