### ISSUE TITLE
LegendProperty "symbolLimit" appears to be missing

### ISSUE THREAD

**Issue by trubens71** [gicentre/elm-vegalite#33]
Having checked the respective source code versions, I believe that the legend property "symbolLimit" was present in Vega-lite v4.8, but is not in elm-vegalite 2.30. This property limits the number of symbols shown in a legend.

Not a big deal, as I can fix manually in the resulting json before publishing, but thought I might as well log this.

**Comment by jwoLondon** [comment]
Thanks very much for spotting this. Yes it was inadvertently missed.

Will be added in the next release.
