### ISSUE TITLE
Hyperlink Properties

### ISSUE THREAD

**Issue by ChrisWellsWood** [gicentre/elm-vegalite#35]
Hello! I've been trying to follow [this example](https://vega.github.io/vega-lite/docs/mark.html#hyperlink) to add hyperlinks to my marks, but I can't find the `href` encoding. In the example, `href` is used in a similar way to both `color` and `tooltip`, which I can find in the package. Is there another way to do this that I'm missing?

**Comment by jwoLondon** [comment]
The function in elm-vegalite is [hyperlink](https://package.elm-lang.org/packages/gicentre/elm-vegalite/latest/VegaLite#hyperlink). Here's an example, which can also be found in the [test-gallery](https://github.com/gicentre/elm-vegalite/blob/47d2d872b0ccae0e29e6ea8429d22d207f86364a/test-gallery/src/GalleryInteraction.elm#L61-L82) of the elm-vegalite distribution where most of the examples in the VegaLite documentation can also be found.

```elm
hyperScatter : Spec
hyperScatter =
    let
        data =
            dataFromUrl "https://cdn.jsdelivr.net/npm/vega-datasets@2.2/data/cars.json" []

        trans =
            transform
                << calculateAs "'https://www.google.com/search?q=' + datum.Name" "url"

        enc =
            encoding
                << position X [ pName "Horsepower", pQuant ]
                << position Y [ pName "Miles_per_Gallon", pQuant ]
                << color [ mName "Origin" ]
                << tooltips [ [ tName "Name" ], [ tName "Year", tTimeUnit year ] ]
                << hyperlink [ hName "url" ]
    in
    toVegaLite [ width 400, height 400, data, trans [], enc [], point [] ]
```
