### ISSUE TITLE
Upgrade to Vega-Lite 5

### ISSUE THREAD

**Issue by eikooc** [gicentre/elm-vegalite#37]
Vega-Lite has come out with a new major version in February. 

This library should be updated to use the latest version.

There are not that many breaking changes it seems
https://github.com/vega/vega-lite/releases/tag/v5.0.0

**Comment by jwoLondon** [comment]
Yes. I've been working on this over the last couple of months – see [this repo's change doc](https://github.com/gicentre/elm-vegalite/blob/main/docs/changeNotes.md) for details. While the breaking changes are relatively small, there is a major change in the selection model used by Vega-Lite and the introduction of [parameters](https://vega.github.io/vega-lite/docs/parameter.html) and [expressions](https://vega.github.io/vega-lite/docs/types.html#exprref) to almost all properties. This has required some major refactoring behind the API.

I expect to release the new version supporting Vega-Lite 5 in the next week or so.

**Comment by jwoLondon** [comment]
The new version (elm-vegalite4.0.0) is now published, which fully supports VegaLite 5.1.

https://package.elm-lang.org/packages/gicentre/elm-vegalite/latest/
