### ISSUE TITLE
remove SReverse in ScaleProperty?

### ISSUE THREAD

**Issue by DougBurke** [gicentre/elm-vegalite#4]
As far as I can tell, `SReverse` in `ScaleProperty` is not generating valid Vega-Lite JSON - it may be Vega instead, but I can't find the string reverse in https://github.com/vega/schema/blob/master/vega-lite/v3.3.0.json 

In hvega I have added a `MSort` constructor to `MarkChannel` to support reversing things (or use `PSort`, I should also check the other relevant types to see if they need their own `xSort`). You can see an example at

https://github.com/DougBurke/hvega/pull/54/commits/6a1e0ed268686ae1fb1edbb835823600896acf88

which adds `MSort` and adjusts two of the `ColorTests` to use `MSort` rather than `SReverse` (I haven't - yet? - followed your lead and moved to a function-based rather than constructor-based API).

**Comment by jwoLondon** [comment]
Thanks for spotting this. As you can probably tell, elm-vegalite doesn't validate against the schema directly, so I don't always catch these inconsistencies.

Hmm. Not sure how `scReverse` became established. It does work, but I agree is not permitted by the schema. I should add `mSort` (with a hidden `MSort`). I don't think there are any additional `xSorts` to handle as `fSort`, `pSort` and `oSort` are already handled and text and hyperlinks are not sortable.

I am not sure whether to remove `scReverse` as it behaves slightly differently to `mSort [soDescending]` for color legends in the ordering of legend items. Perhaps better to deprecate it for now (and this avoids a breaking change).

**Comment by DougBurke** [comment]
I've found sending a visualization to the Vega editor to be a useful test of the spec, since it tells you if there's a problem (at least if I use firefox, it doesnt' seem to work as well on chrome)

**Comment by jwoLondon** [comment]
Added mSort and deprecated scReverse
