### ISSUE TITLE
Granular axis tick label formatting based on timeunit

### ISSUE THREAD

**Issue by RalfNorthman** [gicentre/elm-vegalite#40]
## In pure JSON without elm

When you write the vega-lite specification in json by hand you can give an axis formatting string for each time-unit (see [TimeMultiFormat](https://vega.github.io/vega/docs/types/#TimeMultiFormat)) as in the following example ([open in online vega editor](https://vega.github.io/editor/?#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBWOgCtY3AHaQANOCgB3RgBMW2MAHYADMfURIO9Hkw5QEC7GQBHVsiXxkB+w8c2ATngGIgCMIaYRZhq+kLB43IQG4ZGm5r5QcciJOMkRaTHosAaQeIyoXtFgAL4aVWmQGP4A1sWl8C317vDcOoxK1N6VkAAeg+lQAGaMyGI6rWVe+Q4lAJ6EXjglaITc-uhiapUW6MOMRXZHyxO7GEEX4zEryOj+xQDkAKQAmocPy4jcVj+c5QJpiMAfEQACV+fygqD6rDwyBBkA+UKwHwAspAqnVLrF4PsNmBgKt1sUkfBcb5KjUIDUakA)):
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "width": 700,
  "data": {
    "sequence": {
      "start": -11000000,
      "stop": 10000000,
      "step": 100000,
      "as": "time"
    }
  },
  "mark": "tick",
  "encoding": {
    "x": {
      "field": "time",
      "type": "temporal",
      "axis": {
        "format": {
          "year": "'%Y",
          "hours": "kl %-H",
          "minutes": "%H:%M"
          }
      },
      "scale": {"type": "utc"}    
    }
  }
}
```
This yields the following visualization (notice the different tick label formats depending on the granularity context):

![time-axis-vegalite](https://user-images.githubusercontent.com/26719710/194823326-d1e03aa1-0f09-4de6-a24e-35866799a9f6.png)

This kind of formatting option is especially useful in visualizations with zoom, e.g. you don't have to write both year and seconds (and everything in between) on every tick label).

## In elm-vegalite

I tried to give `axFormat` the whole json map as a string:
```elm
timeExample : Spec
timeExample =
    let
        data_ =
            dataSequenceAs -11000000 10000000 100000 "time"

        myAxis =
            pAxis
                [ axFormatAsTemporal
                , axFormat """{ "year": "`%Y", "hours": "kl %-H", "minutes": "%H:%M" }"""
                ]

        myScale =
            pScale [ scType scUtc ]

        enc =
            encoding
                << position X
                    [ pName "time"
                    , pTemporal
                    , myAxis
                    , myScale
                    ]
    in
    toVegaLite [ width 700, data_, enc [], tick [] ]
```
But then the map is just used as a regular format string:

![vega-lite-time-axis-fail](https://user-images.githubusercontent.com/26719710/194826936-84964c3d-97bf-4131-a7d6-651af321d02a.png)

## Proposal

We probably want to leave `axFormat` as is and introduce some new functions and types like:

 ```elm
axFormatMulti : List TimeUnitFormat -> AxisProperty
tufYear : String -> TimeUnitFormat
tufQuarter : String -> TimeUnitFormat
tufMonth : String -> TimeUnitFormat
tufWeek : String -> TimeUnitFormat
tufDay : String -> TimeUnitFormat
tufDayOfYear : String -> TimeUnitFormat  
tufHours : String -> TimeUnitFormat
tufMinutes : String -> TimeUnitFormat
tufSeconds : String -> TimeUnitFormat
tufMilliseconds : String -> TimeUnitFormat
```

Then the api could look like this:

```elm
 pAxis 
    [ axFormatAsTemporal
    , axFormatMulti
        [ tufYear "`%Y"
        , tufHours "kl %-H"
        , tufMinutes "%H:%M"
        ]
    ]
```

### Notes

I also tried to get a 24-hour clock formatting without AM/PM with just a localization config but that doesn't seem to be possible at the moment: https://github.com/vega/vega/issues/3116

**Comment by jwoLondon** [comment]
Thanks for spotting this (I think the object version of `format` appeared in a recent update that I didn't spot).

I agree we should support multi-format objects for temporal axes. I am keen to keep the expansion of the API to a minimum, so suggest the following, which I think would meet your needs:

```elm
axFormats : List (TimeUnit, String) -> AxisProperty
```

Having a list of time unit and format tuples allows us to reuse [TimeUnit](https://package.elm-lang.org/packages/gicentre/elm-vegalite/latest/VegaLite#TimeUnit) without the need for new formatting functions. So your example would be:

```elm
pAxis [ axFormats [ ( year, "`%Y" ), ( hours, "kl %-H" ), ( minutes, "%H:%M" ) ] ]
```

Or perhaps `axTimeFormats` would be a better name as this only ever applies to temporal formatting (for multiple conditional number formatting we can already use [axDataCondition](https://package.elm-lang.org/packages/gicentre/elm-vegalite/latest/VegaLite#axDataCondition)).

Would that work for you?

**Comment by RalfNorthman** [comment]
Yeah, that sounds great!

Thank you for the rapid response!

**Comment by jwoLondon** [comment]
OK, will implement this now. On balance I think `axTemporalFormats` is a better name given its time-specific context.

**Comment by jwoLondon** [comment]
Now available  as [axTemporalFormats](https://package.elm-lang.org/packages/gicentre/elm-vegalite/latest/VegaLite#axTemporalFormats) in version 5.3.0

**Comment by RalfNorthman** [comment]
Wow, that was quick. It works like a charm!

Thank you so much!
