### ISSUE TITLE
`dtMonthNum` should have the signature `Int -> DateTime`

### ISSUE THREAD

**Issue by RalfNorthman** [gicentre/elm-vegalite#42]
From the source code:

```
{-| Month of a year.
-}
dtMonth : MonthName -> DateTime
dtMonth =
    DTMonth


{-| Month of a year as a number (1 - 12).
-}
dtMonthNum : MonthName -> DateTime
dtMonthNum mon =
    case mon of
        Jan ->
            DTMonthNum (Num 1)

        Feb ->
            DTMonthNum (Num 2)
```

Shouldn't `dtMonthNum` be the following instead?

```
dtMonthNum : Int -> DateTime
dtMonthNum n =
     DTMonthNum (Num n)
```

Otherwise I don't see the point of it when we have `dtMonth`.

**Comment by jwoLondon** [comment]
Thanks for spotting. Embarrassing that I let this one slip through. I've deprecated `dtMonthNum` as it is less safe than using enumerated types. Don't want to remove it entirely yet as this would be a breaking change, but will do so for the next major breaking change release that may be forced by the core VegaLite API.
