### ISSUE TITLE
Suggestion for improvement of the API documentation

### ISSUE THREAD

**Issue by RalfNorthman** [gicentre/elm-vegalite#44]
When I browse the [api documentation](https://package.elm-lang.org/packages/gicentre/elm-vegalite/latest) I often find myself in the following scenario (I use log scaling in this example, but it could be anything):

- I need logarithmic scaling in a visualization.
- I search for 'log' in the searchbar.
- I find [`scLog`](https://package.elm-lang.org/packages/gicentre/elm-vegalite/latest/VegaLite#scLog) and want to use it, but I don't know were to put it in my code.
- It generates a [`Scale`](https://package.elm-lang.org/packages/gicentre/elm-vegalite/latest/VegaLite#Scale), so I click that.
- Here I find functions generating `Scale`, which _can_ be very useful (e.g. if I came here from clicking `Scale` in an input position of a function), but not in this case.
- What I need is a function taking `Scale` as input, i.e. [`scType`](https://package.elm-lang.org/packages/gicentre/elm-vegalite/5.3.0/VegaLite#scType).
- Lets now pretend  [`scType`](https://package.elm-lang.org/packages/gicentre/elm-vegalite/5.3.0/VegaLite#scType) was listed here: I click it.
- I see that `scType` generates a `ScaleProperty`. Now I'm in familiar territory because I recently used `scDomain` which also returns `ScaleProperty`: I now know where to put `scLog` and `scType` in my code.

I think it would be neat if the documentation for each type also had a list of the functions having it as an argument.

**Comment by jwoLondon** [comment]
Thanks for the suggestion. Elm docs production automatically generates links to types used by a function, but not functions that use the given returns type of a function. I agree this makes navigation of complex APIs like this one more challenging. 

I've now added a reasonably comprehensive set of 'parent' function cross-references in the API documentation (as of release 5.4.2) which hopefully addresses this issue for your use-cases.

**Comment by RalfNorthman** [comment]
This is great! Thanks!

I found some typos and broken links that I've tried to fix: #45.
