### ISSUE TITLE
Data ingestion: Apache Arrow

### ISSUE THREAD

**Issue by RalfNorthman** [gicentre/elm-vegalite#46]
I had trouble getting my project to work after I switched from a csv to an arrow data source. As a sanity check I served the elm-vegalite examples folder. All the regular examples seemed to work just fine, but the one with arrow had the same behavior as in my project: empty visualizations and browser dev tools talking about _WARN Data ingestion failed_ and _TypeError: e.Table.from is not a function_.

![arrow-plots-empty](https://user-images.githubusercontent.com/26719710/230002006-74892ffd-eb02-4e26-8219-dffe8dba0f06.png)
![arrow-error-dev-tools](https://user-images.githubusercontent.com/26719710/230002042-c86bcd95-41fe-4f4c-a9fb-a30c0cd54ea9.png)

I was hoping [vega-loader-arrow](https://github.com/vega/vega-loader-arrow) would have a similar example I could test but I just found a link to a deployed observable notebook (that worked).

Is there something wrong on my end (how I serve the files etc) or is this a bigger issue?

EDIT: I just cloned the repo to my local machine and opened the example html-files by clicking on them in the file explorer. Same behaviour.

**Comment by jwoLondon** [comment]
Thanks for raising this one. I've added an issue to Vega-lite as it looks like there has been an API change with vega-loader-arrow:  https://github.com/vega/vega-lite/issues/8898

Will report back here if/when we get a solution.

**Comment by jwoLondon** [comment]
Problem now fixed thanks to [Vega-loader-arrow](https://github.com/vega/vega-loader-arrow/releases/tag/v0.1.0) update from @domoritz to use new arrow API. This shouldn't need any changes for users of elm-vegalite (but you may have to clear caches for any recent arrow tests that were using the older version of Vega-loader-arrow).

**Comment by RalfNorthman** [comment]
This is great news! Thanks!
