### ISSUE TITLE
potentially missing functionality: title, config, and filtering-expressions

### ISSUE THREAD

**Issue by DougBurke** [gicentre/elm-vegalite#6]
Here's a couple of examples from the VegaLite gallery that I couldn't encode (I'm reasonably sure these are missing features, but perhaps I've missed something).  I can split this into 3 tickets if you'd prefer.

*) [Line Charts Showing Ranks Over Time](https://vega.github.io/vega-lite/examples/window_rank.html)

I couldn't set `title` to an object, just a string.

```
  "title": {
    "text": "World Cup 2018: Group F Rankings",
    "frame": "bounds"
  },
```

*) [Mosaic Chart with Labels](https://vega.github.io/vega-lite/examples/rect_mosaic_labelled_with_offset.html)

I think `ConfigurationProperty` is missing a `concat` option:

```
  "config": {
    "view": {
      "stroke": ""
    },
    "concat": {"spacing": 10},
    "axis": {
      "domain": false,
      "ticks": false,
      "labels": false,
      "grid": false
    }
  }
```

*) [Table binned Heatmap](https://vega.github.io/vega-lite/examples/rect_binned_heatmap.html)

This one I can get to work, by manually implementing a "valid" filter, but it is messier than having support in the API. However, this looks like a potentially-invasive change.

The boolean operators expect strings, so we can't combine `fiValid` with `and`

```
  "transform": [{
    "filter": {"and": [
      {"field": "IMDB_Rating", "valid": true},
      {"field": "Rotten_Tomatoes_Rating", "valid": true}
    ]}
  }],
```

**Comment by DougBurke** [comment]
I forgot the following, but it's perhaps less-important (since you can always provide a data source as a JSON object rather than with `dataRow` etc):

*) [Line Chart with Markers and Invalid Values](https://vega.github.io/vega-lite/examples/line_skip_invalid_mid_overlay.html)

I experimentally added a `NullValue` constructor to `DataValue`, but I am not 100% happy with this choice, to be able to represent the following data:

```
    "values": [
      {
        "x": 1,
        "y": 10
      },
      {
        "x": 2,
        "y": 30
      },
      {
        "x": 3,
        "y": null
      },
...
```

**Comment by jwoLondon** [comment]
Thanks very much for these (v. helpful). Would you mind splitting these into 4 separate issues as I think the solutions/discussion around each may be different?

**Comment by DougBurke** [comment]
I've separated them out (linking each back to this for context), so am going to close this ticket.
