### ISSUE TITLE
how to: filter with complicated expressions

### ISSUE THREAD

**Issue by DougBurke** [gicentre/elm-vegalite#8]
From #6 

*) [Table binned Heatmap](https://vega.github.io/vega-lite/examples/rect_binned_heatmap.html)

This one I can get to work, by manually implementing a "valid" filter, but it is messier than having support in the API. However, this looks like a potentially-invasive change.

The boolean operators expect strings, so we can't combine `fiValid` with `and`

```
  "transform": [{
    "filter": {"and": [
      {"field": "IMDB_Rating", "valid": true},
      {"field": "Rotten_Tomatoes_Rating", "valid": true}
    ]}
  }],
```

*) [Calculate Residuals](https://vega.github.io/vega-lite/examples/joinaggregate_residual_graph.html)

The second filter expression here contains a range with a `null` in it and also a `timeUnit` expression, and I couldn't work out how to create it.

```
  "transform": [
    {"filter": "datum.IMDB_Rating != null"},
    {"filter": {"timeUnit": "year", "field": "Release_Date", "range": [null, 2019]}},
```

**Comment by jwoLondon** [comment]
Thanks again for these. It's really helpful in ensuring we have complete coverage of the Vega-Lite API.

There are a couple of ways of replicating the effect of the first table binned heatmap filtering. For 'and' composition, one can simply combine filtering operations:

```elm
trans =
    transform
        << filter (fiValid "IMDB_Rating")
        << filter (fiValid "Rotten_Tomatoes_Rating")
```

But this may not be very efficient if it generates two passes over the data source. 
Alternatively, one can also use an expression with [isValid](https://vega.github.io/vega/docs/expressions/#isValid)

```elm 
trans =
    transform
        << filter (fiExpr "isValid(datum.IMDB_Rating) && isValid(datum.Rotten_Tomatoes_Rating)")
```

But to produce the JSON you illustrate, I have pushed a new function `fiOp` for the next release that will convert any filter into a `BooleanOp` that can be composed with `and`, `or` etc. This has the advantage of type safety compared with the String expression above, although more verbose.

```elm
trans =
    transform
        << filter
            (fiCompose
                (and
                    (fiValid "IMDB_Rating" |> fiOp)
                    (fiValid "Rotten_Tomatoes_Rating" |> fiOp)
                )
            )
```

The new `fiOp` should be especially useful for cases that need to compose data filtering and interactive selection filtering.

**Comment by jwoLondon** [comment]
For your null/date range example, you can use an empty list to represent a null date value:

```elm
filter (fiRange "Release_Date" (dtRange [] [ dtYear 2019 ]))
```
