### ISSUE TITLE
how to: set title options

### ISSUE THREAD

**Issue by DougBurke** [gicentre/elm-vegalite#9]
From #6

*) [Line Charts Showing Ranks Over Time](https://vega.github.io/vega-lite/examples/window_rank.html)

I couldn't set `title` to an object, just a string.

```
  "title": {
    "text": "World Cup 2018: Group F Rankings",
    "frame": "bounds"
  },
```

**Comment by jwoLondon** [comment]
Thanks for raising this. Titles can currently be configured with [coTitle](https://package.elm-lang.org/packages/gicentre/elm-vegalite/latest/VegaLite#coTitle), but this is applied to all titles in a specification so is not always appropriate.

I have pushed a breaking change update for the next release that allows a list of `TitleProperty` options to be specified with `title` to allow a per-title settings. I have also added `frame`, `fontStyle`, `style` and `zIndex` to both `TitleProperty` and `TitleConfig` to bring it in line with the latest Vega-Lite releases.

e.g.

```elm
 title "World Cup 2018: Group F Rankings" [ tiFrame tfBounds ]
```
